Generate array of ints, not of 1-char strings
IonicaBizau/pi-digits pull request #4
Opened 2017-10-15 15:32 UTC by silviubogan

I tested the generator script and also the example, everything works well with the new code.

2017-10-15 15:36 UTC, IonicaBizau requested changes
Yup, this will save some space on the disk!
Thank you.

Maybe add a note in the docs mentioning they are numbers.

2017-10-15 15:36 UTC, IonicaBizau commented on lib/generate-json.js
> +    fs.readFileSync(`${__dirname}/pi.txt`, "utf8").trim().slice(2).split("").map((x) => parseInt(x))
`.map(Number)` would do the same, but it shorter :smile:

2017-10-15 15:55 UTC, silviubogan commented
1. JSDoc comments to the two exported properties, then regenerate DOCUMENTATION.md.
2. In the JSDoc comment of the `decimals` property specify that it is an array of numbers, not of strings.
3. Recommend using [this](https://github.com/vim-scripts/LargeFile) to open pi.json and pi.txt files in VIM and specify a setting I had to do in my `.vimrc` to make this plugin work for me:

```
let g:LargeFile = 1
```

and also say that the default 100 did not work for me.

@IonicaBizau Do you agree with all of these 3 tasks that I want to work upon?

2017-10-15 16:00 UTC, IonicaBizau commented
1. This module is really small (in terms of code), so mentioning in the example, should be enough.
3. Those files shouldn't be edited in any editor.

2017-10-15 17:39 UTC, silviubogan commented
Done! :smiley: I think the changes in 70a2e44 and 9b9e2c3 suffice.

2017-10-18 07:22 UTC, IonicaBizau reviewed
👍

2017-10-18 07:24 UTC, merged